### ISSUE TITLE
イベント名はリソースパスに含めた方が良い気がする

### ISSUE THREAD

**Issue by hhiroshell** [cndjp/qicoo-apireference#4]
e.g.

```
POST /v1/jkd2018/questions
```

イベントをまたぐ質問の一覧取得などはできなくなりますが、そういうケースはほぼないと思うし、いちいちリクエスト毎にイベント名を指定する必要がなくなって良いのでは。

**Comment by Sugi275** [comment]
どちらでもよいのかなぁと、思っています。

POST /v1/jkd2018/questions

参考にしていたサイトのAPIリファレンスが、 /v1/リソース名/ ですべて統一されていたので、Qicooもそうしようかなぁと軽く考えていました。

どちらにしたいという意向も特にないため、ほかの意見がなければhhiroshellさんの書いていただいた内容にしようと思います。
